### ISSUE TITLE
CMake Error HDI_EXTERNAL_FLANN_INCLUDE_DIR-NOTFOUND on initial CMake command Conan build

### ISSUE THREAD

**Issue by N-Dekker** [biovault/HDILib#10]
Issue encountered on branch feature/conan-lite commit 2b736dc5200b6e914390bddae51b5313516698a2

The fist time I run cmake for a build with conan, I get an error.

    D:\HDILib\_build_debug>cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug -DHDILIB_BUILD_WITH_CONAN=ON

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDI_EXTERNAL_FLANN_INCLUDE_DIR
>   used as include directory in directory D:/HDILib/hdi/dimensionality_reduction
>   used as include directory in directory D:/HDILib/hdi/dimensionality_reduction

Apparently commit b1966569dbda9f882cb648b919c95f0f27cd613c did not fix the entire issue.

When I run the same cmake command again, on the same build directory, the error is gone, fortunately!

**Comment by alxvth** [comment]
Fixed in the meantime, flann is linked to in a different manner now
