### ISSUE TITLE
knn_utils.h should be moved to dimensionality_reduction project

### ISSUE THREAD

**Issue by jeggermont** [biovault/HDILib#14]
knn_utils.h which contains enumerated types for KNN algorithms and KNN algorithm distance measures is currently in the utils project. However, the utils project has no information (e.g. defines) regarding supported KNN algorithms. This is currently all handled in the dimensionality_reduction project.

Moving knn_utils.h from the utils project to the dimensionality reduction project would make it a lot easier to add functions which return which KNN algorithm is supported and which distance measure is supported for which KNN algorithm.

It would be possible to add these functions in the dimensionality_reduction project but this leads to information regarding KNN algorithms to be split over several projects.

**Comment by thoellt** [comment]
I agree. Would you take this over?

**Comment by jeggermont** [comment]
Hi Thomas,

Yes I can prepare a branch. I was already working on a branch to add some support functions and moving the knn_utils can easily be part of it.

Jeroen


Leiden University Medical Center | Division of Image Processing (LKEB),  Department of Radiology | PO Box 9600 | Postal zone C2-S | 2300 RC Leiden | The Netherlands

**Comment by alxvth** [comment]
This was implemented in #16
