### ISSUE TITLE
lz4 does not bring Cmake conf files on macOS

### ISSUE THREAD

**Issue by thoellt** [biovault/HDILib#43]
```find_package(lz4)```

does not work, use 

```find_package(PkgConfig REQUIRED)
pkg_check_modules(lz4 REQUIRED IMPORTED_TARGET liblz4)```

instead

**Comment by alxvth** [comment]
Is this still a problem with lz4 version 1.10?

This might be a recent addition, but it is the way [their test package](https://github.com/lz4/lz4/blob/release/tests/cmake/CMakeLists.txt) is set up, with `find_package(lz4 CONFIG REQUIRED)`.
Homebrew now also [provides version 1.10](https://formulae.brew.sh/formula/lz4#default).

I updated the current master to be a bit more robust when linking against lz4 and flann, could you check again?

**Comment by thoellt** [comment]
No, for homebrew lz4 uses pkgconfig for configuration (see below also the lib folder of the lz4 homebrew install)
the above command is the drop in replacement, but add pkgconfig as a macOS dependency of course...

<img width="443" alt="image" src="https://github.com/user-attachments/assets/2fa2dc25-f5f1-4230-abc3-985ae6df803d">

**Comment by alxvth** [comment]
We could use something like this:
```cmake
if(APPLE AND NOT lz4_DIR AND NOT lz4_ROOT)
    # installed lz4 with homebrew
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(lz4 REQUIRED IMPORTED_TARGET liblz4)
    set(LZ4_TARGET liblz4)
else()
    find_package(lz4 CONFIG REQUIRED)
endif()
```

But I have no way of testing that on Mac. Specifically, I don't know which targets are defined. I guess the `liblz4` is a dynamic library that we can link against?

**Comment by thoellt** [comment]
not sure if find_package works with PkgConfig. In my installation it does not bring a cmake folder either (or a lib folder whatsoever, its just an executable)

**Comment by alxvth** [comment]
Looking at [how others use the above snippet](https://github.com/search?q=pkg_check_modules%28lz4+REQUIRED+IMPORTED_TARGET+liblz4%29&type=code) `find_package(PkgConfig REQUIRED)` is used as well before it. But the target then seems to become `PkgConfig::lz4`.

I cannot test this, but maybe you can try this out:
```cmake
if(APPLE AND NOT lz4_DIR AND NOT lz4_ROOT)
    # installed lz4 with homebrew
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(lz4 REQUIRED IMPORTED_TARGET liblz4)
    set(LZ4_TARGET PkgConfig::lz4)
else()
    find_package(lz4 CONFIG REQUIRED)
endif()
```

**Comment by alxvth** [comment]
For older Ubuntu versions (e.g. 20.04 LTS) we also need to setup PkgConfig with `sudo apt install pkg-config` and find the packages differently:

```cmake
find_package(PkgConfig REQUIRED)

pkg_check_modules(lz4 REQUIRED IMPORTED_TARGET liblz4)
set(LZ4_TARGET PkgConfig::lz4)

pkg_check_modules(flann REQUIRED flann)
set(FLANN_TARGET flann_cpp)
set(flann_INCLUDE_DIR "${flann_INCLUDE_DIRS}/flann")
```

**Comment by thoellt** [comment]
It seems to work (as in it allows me to create a project and build it) but it shows the directory as not found in the cmake GUI (note that it gives positive response in the output below)

<img width="771" alt="Screenshot 2024-10-14 at 16 32 35" src="https://github.com/user-attachments/assets/3a573ba2-3aae-4fce-afd7-ee7f0a6c2513">

**Comment by alxvth** [comment]
That's ok. 
CMake's find_package will look into `lz4_DIR` for a config file. If not found there or in other search paths, it populates `lz4_DIR` with the not-found indicator and sets and internal variable `lz4_FOUND` to false. Then, PkgConfig takes over and finds lz4, but does not touch `lz4_DIR` again.
Since the version was printed we know that the internal `lz4_FOUND` was set true though.

It wouldn't make sense to populate `lz4_DIR` manually after PkgConfig found lz4 because there still wouldn't be a cmake config file it could point to...
