### ISSUE TITLE
Bug in void TSNE<scalar_type>::initialize(data::Embedding<scalar_type>* embedding, InitParams params)

### ISSUE THREAD

**Issue by jeggermont** [biovault/HDILib#7]
In tsne_inl.h in the function void TSNE<scalar_type>::initialize(data::Embedding<scalar_type>* embedding, InitParams params) the member variable  '_init_params' is assigned to itself instead of the function parameter 'params' being assinged to  '_init_params'.

Bug was found by clang-1100.0.33.8 on macOS

**Comment by alxvth** [comment]
This was fixed with a19e6e158fa46b7236b90c916c33b0e8ef9f12de
